version: 2

jobs:
  test:
    working_directory: /go/src/github.com/utilitywarehouse/uw-proximo
    docker:
    - image: circleci/golang:1.13
      environment:
        GO111MODULE: "on"
        GOLANGCI_VERSION: "v1.21.0"
    steps:
    - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s ${GOLANGCI_VERSION}
    - run: mv ./bin/golangci-lint $GOPATH/bin/ && rm -rf bin
    - checkout
    - run: go mod download
    - run: make lint
    - run: make test
    - run: make build

workflows:
  version: 2
  test:
    jobs:
      - test
